import type { Photo } from "../types";

export const photos: Photo[] = [
  {
    id: "sunset-cliffs",
    title: "Sunset Cliffs",
    location: "Sunset Beach, Oʻahu",
    date: "2025-03-14",
    imageUrl: "/assets/photos/sunset-cliffs.jpg",
    thumbUrl: "/assets/photos/sunset-cliffs-thumb.jpg",
    tags: ["sunset", "ocean", "landscape"],
    blurb: "The golden hour hits different when the cliffs frame the horizon. Shot on a calm evening with a 24mm lens.",
    camera: "Sony A7III",
  },
  {
    id: "north-shore-swell",
    title: "North Shore Swell",
    location: "Waimea Bay, Oʻahu",
    date: "2025-01-22",
    imageUrl: "/assets/photos/north-shore.jpg",
    thumbUrl: "/assets/photos/north-shore-thumb.jpg",
    tags: ["surf", "ocean", "winter"],
    blurb: "Winter swells on the North Shore are humbling. This was a 15-foot day at Waimea — the sound alone is unforgettable.",
    camera: "Sony A7III",
  },
  {
    id: "windward-coast",
    title: "Windward Coast Dawn",
    location: "Kailua, Oʻahu",
    date: "2024-11-03",
    imageUrl: "/assets/photos/windward-dawn.jpg",
    thumbUrl: "/assets/photos/windward-dawn-thumb.jpg",
    tags: ["sunrise", "landscape", "calm"],
    blurb: "The windward side wakes up slowly. The Koʻolau range catches the first light while the ocean stays glassy.",
    camera: "Fuji X-T4",
  },
  {
    id: "honeymoon-beach",
    title: "Honeymoon Beach",
    location: "Polihale, Kauaʻi",
    date: "2024-07-18",
    imageUrl: "/assets/photos/honeymoon.jpg",
    thumbUrl: "/assets/photos/honeymoon-thumb.jpg",
    tags: ["beach", "sunset", "kauai"],
    blurb: "End of the road on Kauaʻi. The beach stretches miles in both directions and you're usually the only one there.",
    camera: "Fuji X-T4",
  },
  {
    id: "lava-flow",
    title: "Lava Flow at Dawn",
    location: "Hawaiʻi Volcanoes National Park",
    date: "2024-02-11",
    imageUrl: "/assets/photos/lava-dawn.jpg",
    thumbUrl: "/assets/photos/lava-dawn-thumb.jpg",
    tags: ["volcano", "dawn", "big-island"],
    blurb: "Hiked out before sunrise to catch the glow. The heat was intense but the spectacle was worth every step.",
    camera: "Sony A7III",
  },
  {
    id: "molokini-crater",
    title: "Molokini Crater",
    location: "Maui",
    date: "2023-12-26",
    imageUrl: "/assets/photos/molokini.jpg",
    thumbUrl: "/assets/photos/molokini-thumb.jpg",
    tags: ["snorkel", "ocean", "maui"],
    blurb: "The partially submerged crater creates a natural aquarium. Clearest water I've ever seen — 100+ feet visibility.",
    camera: "GoPro Hero 11",
  },
  {
    id: "sailing-hanauma",
    title: "Sailing Hanauma",
    location: "Hanauma Bay, Oʻahu",
    date: "2023-09-15",
    imageUrl: "/assets/photos/hanauma-sail.jpg",
    thumbUrl: "/assets/photos/hanauma-sail-thumb.jpg",
    tags: ["sailing", "ocean", "aerial"],
    blurb: "A bird's-eye view of the bay from a sailboat drone shot. The reef patterns are visible even from altitude.",
    camera: "DJI Mavic 3",
  },
  {
    id: "maui-road",
    title: "Road to Hāna",
    location: "Hāna Highway, Maui",
    date: "2023-06-04",
    imageUrl: "/assets/photos/hana-road.jpg",
    thumbUrl: "/assets/photos/hana-road-thumb.jpg",
    tags: ["road-trip", "jungle", "maui"],
    blurb: "620 curves and 59 bridges. The journey is the destination on this drive through Maui's lush east coast.",
    camera: "Fuji X-T4",
  },
];
